services:

  panel_db_service:
    container_name: 'panel_db'
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: MetalleLmoons2004!
      POSTGRES_DB: postgres
    networks:
      - myNetwork
    volumes:
      - pg-panel-data:/var/lib/postgresql/data
    ports:
      - "6432:5432"

  panel_broker_service:
    container_name: 'panel_broker'
    image: redis:latest
    networks:
      - myNetwork
    ports:
      - "7379:6379"

  tg_panel_service:
    container_name: 'tg_panel'
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - myNetwork
    env_file:
      - .env

  panel_celery_worker_service:
    container_name: 'panel_celery_worker'
    build:
      context: .
    networks:
      - myNetwork
    env_file:
      - .env
    command: "celery --app=src.tasks.celery_app:celery_instance worker -l INFO"

  panel_celery_beat_service:
    container_name: 'panel_celery_beat'
    build:
      context: .
    networks:
      - myNetwork
    env_file:
      - .env
    command: "celery --app=src.tasks.celery_app:celery_instance beat -l INFO"

networks:
  myNetwork:
    external: true

volumes:
  pg-panel-data: