"""prices table

Revision ID: 5eefa376fe76
Revises: 2a02e700bcaf
Create Date: 2025-02-06 18:55:15.468139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5eefa376fe76'
down_revision: Union[str, None] = '2a02e700bcaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_final_price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('redemption_price_in_yuan', sa.Float(), nullable=False),
    sa.Column('yuan_to_ruble_exchange_rate', sa.Float(), nullable=False),
    sa.Column('delivery_price', sa.Float(), nullable=False),
    sa.Column('markup_coefficient', sa.Float(), nullable=False),
    sa.Column('additional_services_price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_final_price')
    # ### end Alembic commands ###
