"""fix_prices

Revision ID: c7f5d2c7f9bf
Revises:
Create Date: 2025-05-01 15:28:16.843935

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c7f5d2c7f9bf"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "data_final_price",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("delivery_price_in_yuan", sa.Float(), nullable=False),
        sa.Column("yuan_to_ruble_exchange_rate", sa.Float(), nullable=False),
        sa.Column("markup_coefficient", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "products_poizon",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("link", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("products_poizon")
    op.drop_table("data_final_price")
    # ### end Alembic commands ###
